### PR TITLE
Expose Pino constructor so that crafty things can be done with it

### PR DESCRIPTION
**Pull request by jsumners**
As the title says...

### CODE REVIEW

**Comment by mcollina** [comment]
There is only one catch here. It is going to be undocumented, and we might change it within a semver-minor. It's an internal API, exposed to help integration. Can you put this in a comment?

Otherwise LGTM

**Comment by davidmarkclements** [comment]
Can we underscore it to signify it's private/for integration?

module.exports._Pino = Pino

**Comment by davidmarkclements** [comment]
You could even use defineProperty to make sure it's non enumerable

**Comment by jsumners** [comment]
Done.

**Comment by mcollina** [comment]
Great, releasing now!

**Pull request merged**
